---
keys:
  - &admin_delora age1dwpdtl429567jsfnqvhw6wykg4kny334m80nmwc6snyhnanxjs7spa8klg
  - &machine_homelab age1pgfaqeehuq82tw0jjhry8sr25vyram5wcmatgfkqaxyyeskshgtscyushn
creation_rules:
  - path_regex: secrets/[^/]+\.ya?ml$
    key_groups:
    - age:
      - *admin_delora
      - *machine_homelab
